import { RouteGroup } from '../../framework/express/types/index.js';
import { OpenAPIConfig, OpenAPISpec, RouteMetadata } from './types.js';
import { zodToOpenAPI } from './zod-converter.js';
import fs from 'fs';

/**
 * OpenAPI Specification Generator
 * 
 * Generates OpenAPI 3.0 specifications from Express routes
 */
export class OpenAPIGenerator {
    private config: Required<OpenAPIConfig>;
    private spec: OpenAPISpec | null = null;

    constructor(config: OpenAPIConfig = {}) {
        this.config = {
            enabled: config.enabled ?? true,
            output: config.output ?? './openapi.json',
            ui: config.ui ?? '/api-docs',
            info: {
                title: config.info?.title ?? 'API Documentation',
                version: config.info?.version ?? '1.0.0',
                description: config.info?.description ?? 'API documentation generated by express-pack',
            },
            servers: config.servers ?? [
                { url: 'http://localhost:3000', description: 'Development server' },
            ],
            security: config.security ?? [],
        };
    }

    /**
     * Generate OpenAPI specification from routes
     */
    generate(routes: RouteGroup[]): OpenAPISpec {
        const paths: Record<string, any> = {};
        const components: any = {
            schemas: {},
            securitySchemes: {
                bearerAuth: {
                    type: 'http',
                    scheme: 'bearer',
                    bearerFormat: 'JWT',
                },
            },
        };

        // Extract paths from routes
        routes.forEach(({ prefix = '', version = '', route: routeList = [] }) => {
            const basePath = prefix + version;

            routeList.forEach(({ path, route }) => {
                const fullPath = basePath + path;
                paths[fullPath] = this.extractRouteInfo(route);
            });
        });

        this.spec = {
            openapi: '3.0.0',
            info: this.config.info,
            servers: this.config.servers,
            paths,
            components,
        };

        return this.spec!;
    }

    /**
     * Extract route information from Express router
     */
    private extractRouteInfo(router: any): any {
        const methods: any = {};

        // Iterate through router stack
        router.stack?.forEach((layer: any) => {
            if (layer.route) {
                const { path, methods: routeMethods } = layer.route;

                Object.keys(routeMethods).forEach((method) => {
                    if (routeMethods[method]) {
                        methods[method] = this.generateMethodDoc(layer, method);
                    }
                });
            }
        });

        return methods;
    }

    /**
     * Generate documentation for a specific HTTP method
     */
    private generateMethodDoc(layer: any, method: string): any {
        // Extract from metadata if available
        const metadata: RouteMetadata = layer.route?.metadata || {};

        return {
            summary: metadata.summary || `${method.toUpperCase()} endpoint`,
            description: metadata.description || '',
            tags: metadata.tags || [],
            parameters: this.extractParameters(metadata),
            requestBody: this.extractRequestBody(metadata),
            responses: this.extractResponses(metadata),
            security: metadata.requiresAuth ? [{ bearerAuth: [] }] : undefined,
        };
    }

    /**
     * Extract parameters from metadata
     */
    private extractParameters(metadata: RouteMetadata): any[] {
        const params: any[] = [];

        // Path parameters
        if (metadata.params) {
            Object.keys(metadata.params).forEach((name) => {
                params.push({
                    name,
                    in: 'path',
                    required: true,
                    schema: zodToOpenAPI(metadata.params![name]),
                });
            });
        }

        // Query parameters
        if (metadata.query) {
            Object.keys(metadata.query).forEach((name) => {
                params.push({
                    name,
                    in: 'query',
                    required: false,
                    schema: zodToOpenAPI(metadata.query![name]),
                });
            });
        }

        return params;
    }

    /**
     * Extract request body from metadata
     */
    private extractRequestBody(metadata: RouteMetadata): any {
        if (!metadata.body) return undefined;

        return {
            required: true,
            content: {
                'application/json': {
                    schema: zodToOpenAPI(metadata.body),
                },
            },
        };
    }

    /**
     * Extract responses from metadata
     */
    private extractResponses(metadata: RouteMetadata): any {
        return {
            200: {
                description: 'Successful response',
                content: {
                    'application/json': {
                        schema: metadata.response || { type: 'object' },
                    },
                },
            },
            400: {
                description: 'Bad request',
                content: {
                    'application/json': {
                        schema: {
                            type: 'object',
                            properties: {
                                success: { type: 'boolean', example: false },
                                error: { type: 'string' },
                                code: { type: 'string' },
                            },
                        },
                    },
                },
            },
            401: {
                description: 'Unauthorized',
            },
            500: {
                description: 'Internal server error',
            },
        };
    }

    /**
     * Save specification to file
     */
    saveToFile(filepath?: string): void {
        if (!this.spec) {
            throw new Error('No specification generated. Call generate() first.');
        }

        const path = filepath || this.config.output;
        fs.writeFileSync(path, JSON.stringify(this.spec, null, 2));
    }

    /**
     * Get generated specification
     */
    getSpec(): OpenAPISpec | null {
        return this.spec;
    }
}
